"""
Plain-text chord chart exporter.
Generates musician-readable chord sheets with sections and bar delimiters.
"""

from backend.models.schemas import SongAnalysis
from backend.export.pdf_exporter import format_bar_str


def export_to_txt(analysis: SongAnalysis) -> str:
    """Formats the song analysis as a clean monospace text chord chart matching musician lead sheets."""
    lines = []
    lines.append("=" * 60)
    lines.append(analysis.title.upper())
    lines.append("=" * 60)
    scale_str = analysis.key.display.replace(" Major", "").replace(" Minor", "m")
    lines.append(f"Meter: {analysis.meter.display}")
    lines.append(f"Tempo: {analysis.tempo.bpm:.0f} BPM" + (" (estimated)" if analysis.tempo.is_estimated else ""))
    lines.append(f"Scale: {scale_str}")
    lines.append(f"Duration: {int(analysis.metadata.duration // 60)}:{int(analysis.metadata.duration % 60):02d}")
    if analysis.transpose_semitones != 0:
        lines.append(f"Transposition: {analysis.transpose_semitones:+d} semitones")
    lines.append("-" * 60)
    lines.append("")

    for sec in analysis.sections:
        raw_name = sec.name.strip()
        if raw_name.upper().startswith("SECTION "):
            remainder = raw_name[8:].strip()
            if "(Repeat)" in remainder:
                letter = remainder.replace("(Repeat)", "").strip()
                display_name = f"Sec {letter} (Rep):"
            else:
                display_name = f"Sec {remainder}:"
        elif raw_name.upper() == "INTRO":
            display_name = "Intro:"
        elif raw_name.upper() == "OUTRO":
            display_name = "Outro:"
        elif raw_name.upper() in ["CHORUS", "CH"]:
            display_name = "CH:"
        elif not raw_name.endswith(":"):
            display_name = f"{raw_name.capitalize()}:"
        else:
            display_name = raw_name

        # Break bars into rows of 4
        bar_rows = []
        for i in range(0, len(sec.bars), 4):
            bar_rows.append(sec.bars[i : i + 4])

        for r_idx, row_bars in enumerate(bar_rows):
            prefix = f"{display_name:<12}" if r_idx == 0 else " " * 12
            bar_strs = [format_bar_str(b) for b in row_bars]
            lines.append(f"{prefix}|{'|'.join(bar_strs)}|")
        lines.append("")

    lines.append("-" * 60)
    lines.append(f"Generated by Song Chord Analyzer | Model: {analysis.pipeline_metadata.model_name}")
    lines.append("=" * 60)

    return "\n".join(lines)
